version: 0.2
phases:
  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR/infrastructure/setup
      - echo run terraform initialization $CODEBUILD_SRC_DIR/infrastructure
      - terraform init
      - terraform validate

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/infrastructure/setup
     
      - terraform plan    

